name: Use Reusable MkDocs Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-docs:
    uses: Telucero/workflows/.github/workflows/check-mkdocs-build.yml@Central_repo_test  # Specify the branch name here
    with:
      mkdocs_repo: Telucero/moonbeam-mkdocs  # or the appropriate repo for the client
      docs_dir: docs
      deploy: false
